<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="i18n/*.json" />
    <EmbeddedResource Include="Assets/Sounds/*" />
    <None Include="Assets/Icons/**/*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets/PROVENANCE.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Headless" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <ProjectReference Include="../StalkerSaveEditor.Core/StalkerSaveEditor.Core.csproj" />
    <ProjectReference Include="../StalkerSaveEditor.Steam/StalkerSaveEditor.Steam.csproj" />
    <ProjectReference Include="../StalkerSaveEditor.Updater/StalkerSaveEditor.Updater.csproj" />
  </ItemGroup>
</Project>
