using StalkerSaveEditor.Core.Diagnostics;
using System.Text.Json.Serialization;

namespace StalkerSaveEditor.Core.Patching;

[JsonConverter(typeof(JsonStringEnumConverter<GameFixPreset>))]
public enum GameFixPreset
{
    EssentialOnly,
    Recommended,
    AllSafeFixes,
    Custom,
}

/// <summary>Evidence-backed fix definitions shipped by this application.</summary>
public static class GameFixCatalog
{
    private static readonly IReadOnlyList<GameFixDefinition> Definitions =
    [
        new GameFixDefinition(
            "cs.quest.dead-wild-napr",
            GameTarget.ClearSky,
            "1.0.0",
            "Stop Flea Market quests after Wild Napr dies",
            ["11450472"],
            GameFixCategory.Essential,
            GameFixMaturity.Validated,
            [],
            [],
            [
                new TextPatchOperation(
                    "gamedata/configs/creatures/spawn_sections_garbage.ltx",
                    "character_profile     = gar_digger_quester\r\n",
                    "character_profile     = gar_digger_quester\r\non_death             = %+gar_flea_market_stop_quest_line%\r\n")
                {
                    ExpectedFileSha256 = "029ddb9331d44c8c0d6aaf3a5791bbb53f7e738c8efba7fc121a30a90a0a5078",
                },
            ],
            "Adapted from SRP v1.1.5; the target is limited to the verified Clear Sky Steam build.")
        {
            Problem = "Wild Napr can die while offline without stopping his storyline tasks; later tasks can target a missing logic@work5 and crash.",
            Description = "Adds the NPC death info-portion used by Clear Sky's task definitions to stop the Flea Market quest line. Only deaths processed after this change are covered; existing affected saves were not verified.",
            Implementation = GameFixImplementationType.ExactTextReplacement,
            RequiresNewGame = false,
            SaveCompatibility = GameFixSaveCompatibility.Unknown,
            VerificationState = GameFixVerificationState.RetailFilesVerified,
            DetectionMethod = "Exact SHA-256 of the effective spawn_sections_garbage.ltx from Steam build 11450472 and one unique CRLF text anchor.",
            References = ["https://github.com/Decane/SRP/blob/master/SRP%20v1.1.5%20-%20Version%20History.txt"],
        },
        SrpFix(
            "cs.quest.flood-underground-duty-goodwill",
            "Award Flood the Underground task goodwill to Duty",
            "The task-giver is a Duty commander, but the task record assigns the Clear Sky faction, so the wrong faction receives goodwill.",
            "Changes only the faction argument for the task issued after the Agroprom Underground sequence.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/agroprom_underground/agru_quest_line.ltx",
                "give_inited_task(storyline:agru_leader_dolg_task:csky)",
                "give_inited_task(storyline:agru_leader_dolg_task:dolg)",
                "340e9b8ca484acfc466ee65f8d135b7045b5dd3e43d64b3bf21f765f6bea9f97")),
        SrpFix(
            "cs.quest.wolf-offline-cancellation",
            "Close Wolf's rescue tasks after failure or offline death",
            "Wolf's death can go unnoticed while offline, leaving his reward and rescue tasks active without a completion path.",
            "Adds Wolf's death info-portion to his spawn record and follows the SRP quest-state exits for the related rescue tasks.",
            GameFixCategory.Essential,
            Patch("gamedata/configs/creatures/spawn_sections_escape.ltx",
                "character_profile     = esc_wolf\r\n",
                "character_profile     = esc_wolf\r\non_death             = %+esc_wolf_dead%\r\n",
                "47c254c9974ac2d4295e1be66e7d7281e121feb98b45415a73944894c512cd89"),
            Patch("gamedata/configs/scripts/escape/esc_quest_additional_line.ltx",
                "on_info = {+esc_wolf_brother_2} sr_idle@3 %=give_inited_task(storyline:esc_additional_quest_4b:stalker)%\r\n",
                "on_info = {+esc_wolf_brother_2} sr_idle@3 %=give_inited_task(storyline:esc_additional_quest_4b:stalker)%\r\non_info2 = {+esc_wolf_brother_fail} sr_idle@4, {=gulag_enemy_actor(esc_smart_terrain_2_12)} sr_idle@4\r\n",
                "28f3a7ed34a4c43a1760f31b984befecf2526fcd8343699f27830c6e189bef78"),
            Patch("gamedata/configs/scripts/escape/esc_quest_additional_line.ltx",
                "on_info = {+esc_wolf_brother_3} sr_idle@4 %=give_inited_task(storyline:esc_additional_quest_4c:stalker)%\r\n",
                "on_info = {+esc_wolf_brother_3} sr_idle@4 %=give_inited_task(storyline:esc_additional_quest_4c:stalker)%\r\non_info2 = {+esc_wolf_brother_fail} sr_idle@4, {=gulag_enemy_actor(esc_smart_terrain_2_12)} sr_idle@4, {+esc_wolf_dead} sr_idle@4\r\n",
                "28f3a7ed34a4c43a1760f31b984befecf2526fcd8343699f27830c6e189bef78"),
            Patch("gamedata/configs/scripts/escape/esc_quest_additional_line_2.ltx",
                "on_info = {+esc_wolf_novice_2} sr_idle@3 %=give_inited_task(storyline:esc_additional_quest_5b:stalker)%\r\n",
                "on_info = {+esc_wolf_novice_2} sr_idle@3 %=give_inited_task(storyline:esc_additional_quest_5b:stalker)%\r\non_info2 = {+esc_stalker_novice_fail} sr_idle@4, {=gulag_enemy_actor(esc_smart_terrain_2_12)} sr_idle@4\r\n",
                "2108c3cda393b6b2c8dceab17be512f222bb701abbd4ff43396f6325c57e3ba9"),
            Patch("gamedata/configs/scripts/escape/esc_quest_additional_line_2.ltx",
                "on_info = {+esc_wolf_novice_3} sr_idle@4 %=give_inited_task(storyline:esc_additional_quest_5c:stalker)%\r\n",
                "on_info = {+esc_wolf_novice_3} sr_idle@4 %=give_inited_task(storyline:esc_additional_quest_5c:stalker)%\r\non_info2 = {+esc_stalker_novice_fail} sr_idle@4, {=gulag_enemy_actor(esc_smart_terrain_2_12)} sr_idle@4, {+esc_wolf_dead} sr_idle@4\r\n",
                "2108c3cda393b6b2c8dceab17be512f222bb701abbd4ff43396f6325c57e3ba9")),
        SrpFix(
            "cs.ai.snork-aggression-key",
            "Restore the dead-camp snork's aggression flag",
            "The encounter uses the misspelled `agressive` key, which the game does not recognize.",
            "Corrects the single LTX key spelling in the Garbage dead-camp snork logic.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/garbage/gar_dead_camp_snork.ltx",
                "agressive = true\r\n", "aggressive = true\r\n",
                "a8a717e6f22fb20bff8a1c9315d2148ef33c3960e4d8a3fccb7ec82aabf1dd6c")),
        SrpFix(
            "cs.ai.agroprom-bloodsucker-aggression",
            "Restore aggression for the Agroprom lair bloodsucker",
            "The lair logic uses the legacy `aggressive_home` token instead of the parameter recognized by the current mob-home scheme.",
            "Updates the single Agroprom additional-task bloodsucker logic flag from SRP.",
            GameFixCategory.Recommended,
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_bloodsucker_home.ltx", "[mob_home]\r\npath_home = agr_additional_quest_2_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "bd610d34287611dc520094f7e389d2e8a20afbb2be794737039ca09378c595ac")),
        SrpFix(
            "cs.ai.agroprom-dogs-aggression",
            "Restore aggression for the Agroprom dog packs",
            "The ten scripted Agroprom dog logic files use the legacy mob-home aggression token, so their assigned attack behavior is not enabled as intended.",
            "Corrects the one flag in each of the ten Agroprom dog logic files, matching SRP's explicit aggression parameter.",
            GameFixCategory.Recommended,
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_1.ltx", "[mob_home]\r\npath_home = agr_dogs_home_1\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "5d3392c551545e5ab0663775c66f741ae39240b738d55fc96b3c3f57fa1bd548"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_2.ltx", "[mob_home]\r\npath_home = agr_dogs_home_1\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "5d3392c551545e5ab0663775c66f741ae39240b738d55fc96b3c3f57fa1bd548"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_3.ltx", "[mob_home]\r\npath_home = agr_dogs_home_1\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "5d3392c551545e5ab0663775c66f741ae39240b738d55fc96b3c3f57fa1bd548"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_4.ltx", "[mob_home]\r\npath_home = agr_dogs_home_1\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "5d3392c551545e5ab0663775c66f741ae39240b738d55fc96b3c3f57fa1bd548"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_5.ltx", "[mob_home]\r\npath_home = agr_dogs_home_1\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "5d3392c551545e5ab0663775c66f741ae39240b738d55fc96b3c3f57fa1bd548"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_6.ltx", "[mob_home]\r\npath_home = agr_dogs_home_2\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "6799a99678673bf028b8d5ef059c5d657645f9b94c5427977dc089e6d973b9e1"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_7.ltx", "[mob_home]\r\npath_home = agr_dogs_home_2\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "6799a99678673bf028b8d5ef059c5d657645f9b94c5427977dc089e6d973b9e1"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_8.ltx", "[mob_home]\r\npath_home = agr_dogs_home_2\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "6799a99678673bf028b8d5ef059c5d657645f9b94c5427977dc089e6d973b9e1"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_9.ltx", "[mob_home]\r\npath_home = agr_dogs_home_2\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "6799a99678673bf028b8d5ef059c5d657645f9b94c5427977dc089e6d973b9e1"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_dog_10.ltx", "[mob_home]\r\npath_home = agr_dogs_home_2\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "6799a99678673bf028b8d5ef059c5d657645f9b94c5427977dc089e6d973b9e1")),
        SrpFix(
            "cs.ai.agroprom-scientist-bloodsucker-aggression",
            "Restore aggression for the scientists' bloodsuckers",
            "Both scripted mob-home states use the legacy aggression token rather than the current scheme parameter.",
            "Corrects only the two explicit Agroprom scientist bloodsucker states from SRP.",
            GameFixCategory.Recommended,
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_scientists_bloodsucker_logic.ltx", "[mob_home]\r\npath_home = agr_scientists_bloodsucker_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "5aa2ec88ca0a55e4bf261106c0b5d79d99d9c8842cbf7e219b07843215077b7d"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_scientists_bloodsucker_logic.ltx", "[mob_home@2]\r\npath_home = agr_scientists_bloodsucker_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "5aa2ec88ca0a55e4bf261106c0b5d79d99d9c8842cbf7e219b07843215077b7d")),
        SrpFix(
            "cs.ai.agroprom-snork-wave-aggression",
            "Restore aggression for the Agroprom snork wave",
            "All five snork mob-home states use the legacy aggression token, so the scripted wave does not use its intended aggressive behavior.",
            "Corrects each distinct snork waypoint state exactly as SRP does.",
            GameFixCategory.Recommended,
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_snork_attack.ltx", "[mob_home@1]\r\npath_home = jump_snork_1\r\nout_restr = agr_smart_terrain_4_6_def\r\naggressive_home\r\n", "4192b01cbf0e784ebd2ba280af91e8acff5dfeb445ba8725c6a5df56cb4d50e6"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_snork_attack.ltx", "[mob_home@2]\r\npath_home = jump_snork_2\r\nout_restr = agr_smart_terrain_4_6_def\r\naggressive_home\r\n", "4192b01cbf0e784ebd2ba280af91e8acff5dfeb445ba8725c6a5df56cb4d50e6"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_snork_attack.ltx", "[mob_home@3]\r\npath_home = jump_snork_3\r\nout_restr = agr_smart_terrain_4_6_def\r\naggressive_home\r\n", "4192b01cbf0e784ebd2ba280af91e8acff5dfeb445ba8725c6a5df56cb4d50e6"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_snork_attack.ltx", "[mob_home@4]\r\npath_home = jump_snork_4\r\nout_restr = agr_smart_terrain_4_6_def\r\naggressive_home\r\n", "4192b01cbf0e784ebd2ba280af91e8acff5dfeb445ba8725c6a5df56cb4d50e6"),
            LegacyAggressionPatch("gamedata/configs/scripts/agroprom/agr_snork_attack.ltx", "[mob_home@5]\r\npath_home = jump_snork_5\r\nout_restr = agr_smart_terrain_4_6_def\r\naggressive_home\r\n", "4192b01cbf0e784ebd2ba280af91e8acff5dfeb445ba8725c6a5df56cb4d50e6")),
        SrpFix(
            "cs.ai.escape-rescue-dog-aggression",
            "Restore aggression for the Escape rescue dogs",
            "The ten dog mob-home states used by the Escape rescue logic carry the legacy aggression token instead of the current scheme parameter.",
            "Corrects only the ten named dog states in the rescue encounter file.",
            GameFixCategory.Recommended,
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog01]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog01a]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog02]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog02a]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog03]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog03a]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog04]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog04a]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog05]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751"),
            LegacyAggressionPatch("gamedata/configs/scripts/escape/esc_smart_terrain_5_12_works.ltx", "[mob_home@dog05a]\r\npath_home = agr_stalker_novice_quest_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home", "ecf9d3417029c1a615d2aed4b3960d5b58b2732e6388d1b840b40e2b48a46751")),
        SrpFix(
            "cs.ai.military-dog-aggression",
            "Restore aggression for the Military dog packs",
            "The five Military dog logic files also carry the legacy aggression token, leaving their scripted home behavior without the intended aggression flag.",
            "Updates the five identical retail script variants to the explicit parameter used by SRP.",
            GameFixCategory.Recommended,
            LegacyAggressionPatch("gamedata/configs/scripts/military/mil_dog_1.ltx", "[mob_home]\r\npath_home = mil_dogs_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "3232772b9d9ba01a959f8a194df2fca3c2ed22a3a69c9bf3d7ade233086f49df"),
            LegacyAggressionPatch("gamedata/configs/scripts/military/mil_dog_2.ltx", "[mob_home]\r\npath_home = mil_dogs_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "3232772b9d9ba01a959f8a194df2fca3c2ed22a3a69c9bf3d7ade233086f49df"),
            LegacyAggressionPatch("gamedata/configs/scripts/military/mil_dog_3.ltx", "[mob_home]\r\npath_home = mil_dogs_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "3232772b9d9ba01a959f8a194df2fca3c2ed22a3a69c9bf3d7ade233086f49df"),
            LegacyAggressionPatch("gamedata/configs/scripts/military/mil_dog_4.ltx", "[mob_home]\r\npath_home = mil_dogs_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "3232772b9d9ba01a959f8a194df2fca3c2ed22a3a69c9bf3d7ade233086f49df"),
            LegacyAggressionPatch("gamedata/configs/scripts/military/mil_dog_5.ltx", "[mob_home]\r\npath_home = mil_dogs_home\r\nhome_min_radius = 10\r\nhome_max_radius = 30\r\naggressive_home\r\n", "3232772b9d9ba01a959f8a194df2fca3c2ed22a3a69c9bf3d7ade233086f49df")),
        SrpFix(
            "cs.ai.red-forest-bloodsucker-aggression",
            "Restore aggression for the Red Forest bloodsucker groups",
            "The scripted Red Forest bloodsucker home states use the legacy aggression key where SRP specifies the current `aggressive` parameter.",
            "Corrects the active hunter state and all nine runner states while preserving their waypoints and radii.",
            GameFixCategory.Recommended,
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_hunter.ltx", "[mob_home@sound]\r\npath_home = red_bloodsucker_swarm_4_2\r\nhome_min_radius = 30\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "e0cb97dba52afeb5e10d647a2699b1f7a2998b824786a16b9f8b19a3467f4321"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner.ltx", "[mob_home@sound]\r\npath_home = red_bloodsucker_swarm_1_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "7166c3563f623486a943ecac0d3a1e524ce32b7dbe27c6846d43a98994d4d009"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner.ltx", "[mob_home]\r\npath_home = red_bloodsucker_swarm_1_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "7166c3563f623486a943ecac0d3a1e524ce32b7dbe27c6846d43a98994d4d009"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner.ltx", "[mob_home@2]\r\npath_home = red_bloodsucker_swarm_1_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "7166c3563f623486a943ecac0d3a1e524ce32b7dbe27c6846d43a98994d4d009"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner2.ltx", "[mob_home@sound]\r\npath_home = red_bloodsucker_swarm_2_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "968e71e4eb431746140906913adaa0f87d604f83518abda08fb3e76c3074209a"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner2.ltx", "[mob_home]\r\npath_home = red_bloodsucker_swarm_2_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "968e71e4eb431746140906913adaa0f87d604f83518abda08fb3e76c3074209a"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner2.ltx", "[mob_home@2]\r\npath_home = red_bloodsucker_swarm_2_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "968e71e4eb431746140906913adaa0f87d604f83518abda08fb3e76c3074209a"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner3.ltx", "[mob_home@sound]\r\npath_home = red_bloodsucker_swarm_3_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "7aada22f069f3f255a260b9587de29f0a707439aecd53806014ca4a95f608190"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner3.ltx", "[mob_home]\r\npath_home = red_bloodsucker_swarm_3_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "7aada22f069f3f255a260b9587de29f0a707439aecd53806014ca4a95f608190"),
            LegacyAggressionPatch("gamedata/configs/scripts/red_forest/red_bloodsucker_runner3.ltx", "[mob_home@2]\r\npath_home = red_bloodsucker_swarm_3_1\r\nhome_min_radius = 50\r\nhome_max_radius = 50\r\naggressive_home = true\r\n", "7aada22f069f3f255a260b9587de29f0a707439aecd53806014ca4a95f608190")),
        SrpFix(
            "cs.ai.limansk-sniper-look-path",
            "Use the sniper's look waypoint in Limansk",
            "The waiting sniper uses its walking waypoint as the look target, so its scripted facing direction is wrong.",
            "Changes only the look-path reference in the wait state to the dedicated look waypoint already used by the same encounter.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/limansk/lim_final_sniper.ltx",
                "path_look = lim_final_sniper_attack_walk\r\n",
                "path_look = lim_final_sniper_attack_look\r\n",
                "4e270b8d37fc42d852ac54ad8a8a198ce1c2c21580923ff7bf3b4bf846519063")),
        SrpFix(
            "cs.quest.skip-destroyed-limansk-minigun-task",
            "Do not issue the destroyed Limansk minigun task",
            "The Limansk task zone can issue the machine-gun nest task after the bandit-house or ambush state has already advanced.",
            "Adds the two exact progression guards from SRP to the task trigger.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/limansk/lim_destroy_bandit_minigun_task_zone.ltx",
                "on_info = {+lim_destroy_bandit_minigun_task} nil %=give_inited_task(storyline:lim_destroy_bandit_minigun:csky)%",
                "on_info = {+lim_destroy_bandit_minigun_task -lim_bandit_house_go -lim_csky_in_ambush} nil %=give_inited_task(storyline:lim_destroy_bandit_minigun:csky)%, {+lim_bandit_house_go} nil, {+lim_csky_in_ambush} nil",
                "1dbed3607167b8b394260fb49b6675b77caeeb164aa0212addd4e94e38e3e6dd")),
        SrpFix(
            "cs.quest.unique-limansk-commander-task",
            "Issue the return-to-commander task only once",
            "Leaving and re-entering the space restrictor can issue repeated copies of the Limansk return-to-commander task.",
            "Adds the upstream info-portion guard to the single task-issue transition.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/limansk/lim_final_squad_commander_restr.ltx",
                "on_actor_outside = sr_idle@check %=give_inited_task(storyline:lim_electro_fence_actor_come_back:csky)%\r\n",
                "on_actor_outside = {-lim_electro_fence_actor_come} sr_idle@check %=give_inited_task(storyline:lim_electro_fence_actor_come_back:csky)%\r\n",
                "17813d31590b60d3a4751c6ee33409c7fa25ff21b24a70b38f4c7f591bafab6f")),
        SrpFix(
            "cs.quest.agroprom-task-repeat-6-4",
            "Stop the Agroprom 6-4 eliminate-task trigger after issuance",
            "The scripted task trigger returns to its active polling state after issuing the same eliminate task.",
            "Replaces the repeating state transition with the upstream terminal transition.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/agroprom/agr_stalker_base_addition_tasks.ltx",
                "on_info = {+agr_smart_terrain_6_4_simulation_task =smart_captured_by_faction(agr_smart_terrain_6_4:bandit)} sr_idle@line_1 %=give_inited_task(eliminate_smart:agr_smart_terrain_6_4:stalker)%\r\n",
                "on_info = {+agr_smart_terrain_6_4_simulation_task =smart_captured_by_faction(agr_smart_terrain_6_4:bandit)} nil %=give_inited_task(eliminate_smart:agr_smart_terrain_6_4:stalker)%\r\n",
                "b5274333b2bf90fd17397de02cf74bf5878e6bf91cc35fc1b95fbbc16894aa56")),
        SrpFix(
            "cs.quest.agroprom-task-repeat-2-3",
            "Stop the Agroprom 2-3 eliminate-task trigger after issuance",
            "The scripted task trigger returns to its active polling state after issuing the same eliminate task.",
            "Replaces the repeating state transition with the upstream terminal transition.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/agroprom/agr_stalker_base_addition_tasks_2.ltx",
                "on_info = {+agr_smart_terrain_2_3_simulation_task =smart_captured_by_faction(agr_smart_terrain_2_3:bandit)} sr_idle@line_1 %=give_inited_task(eliminate_smart:agr_smart_terrain_2_3:stalker)%\r\n",
                "on_info = {+agr_smart_terrain_2_3_simulation_task =smart_captured_by_faction(agr_smart_terrain_2_3:bandit)} nil %=give_inited_task(eliminate_smart:agr_smart_terrain_2_3:stalker)%\r\n",
                "b8939cbf64ae3649f76bb1280a8d7827dc8e0bc1f68bc9f9cf1cc687034820f2")),
        SrpFix(
            "cs.quest.agroprom-task-repeat-4-2",
            "Stop the Agroprom 4-2 eliminate-task trigger after issuance",
            "The scripted Agroprom 4-2 snork task uses a two-state loop that can issue the same task repeatedly and couples task issuance to squad spawning.",
            "Uses SRP's two mutually exclusive terminal transitions: issue the task when the squad is absent, or create it and issue the task when the expected squad is present.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/agroprom/agr_stalker_base_addition_tasks_3.ltx",
                "on_info = {+agr_smart_terrain_4_2_simulation_task -agr_smart_terrain_4_2_simulation_task_complete =smart_squad_population(monster:agr_smart_terrain_4_2:2)} sr_idle@line_1 %=create_squad(agr_smart_terrain_4_2_snorks_4_lair:agr_smart_terrain_4_2)% \r\n",
                "on_info = {+agr_smart_terrain_4_2_simulation_task !smart_squad_population(monster:agr_smart_terrain_4_2:2)} nil %=give_inited_task(eliminate_smart:agr_smart_terrain_4_2:stalker)%\r\non_info2 = {+agr_smart_terrain_4_2_simulation_task =smart_squad_population(monster:agr_smart_terrain_4_2:2)} nil %=create_squad(agr_smart_terrain_4_2_snorks_4_lair:agr_smart_terrain_4_2) =give_inited_task(eliminate_smart:agr_smart_terrain_4_2:stalker)%\r\n",
                "379b7ab1fec9744bf6eb390683fb59dfb71aade6d8395894bc6351b7cf8e4a21")),
        SrpFix(
            "cs.quest.cancel-strelok-teleport-tasks",
            "Cancel the Strelok teleport tasks when their target is gone",
            "The two additional tasks to follow Strelok toward the generators remain active if he dies or leaves before their completion conditions occur.",
            "Adds the SRP reversed conditions for both task records without changing their completion conditions.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/misc/tm_stancia_2.ltx",
                "condlist_0 = {+stc_additional_q1} complete\r\n",
                "condlist_0 = {+stc_additional_q1} complete\r\ncondlist_1 = {+stc_strelok_dead} reversed\r\ncondlist_2 = {+stc_strelok_gone} reversed\r\n",
                "bf9741c7462e5243c805d043ad4cedb7614621464afd71103c93e8c43bf41945"),
            Patch("gamedata/configs/misc/tm_stancia_2.ltx",
                "condlist_0 = {+stc_second_teleport_actor_out} complete\r\n",
                "condlist_0 = {+stc_second_teleport_actor_out} complete\r\ncondlist_1 = {+stc_strelok_dead} reversed\r\ncondlist_2 = {+stc_strelok_gone} reversed\r\n",
                "bf9741c7462e5243c805d043ad4cedb7614621464afd71103c93e8c43bf41945")),
        SrpFix(
            "cs.quest.hospital-sniper-objective-reversal",
            "Do not complete Hospital defense objectives when they reverse",
            "Each sniper-defense task marks its completion info-portion both on normal completion and on reversal, allowing a failed objective to unlock later steps as though it had succeeded.",
            "Comments out only the four erroneous reversal actions, matching SRP's quest-table correction.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/misc/tm_hospital.ltx",
                "on_reversed = %+hosp_task_sniper_back_rush_1_complete%\r\n",
                ";on_reversed = %+hosp_task_sniper_back_rush_1_complete%\r\n",
                "35d683dcd5015d08a7df6f2b2d62e6a4976642d4edaae34b89edb1c2d9ccd5c1"),
            Patch("gamedata/configs/misc/tm_hospital.ltx",
                "on_reversed = %+hosp_task_sniper_back_rush_2_complete%\r\n",
                ";on_reversed = %+hosp_task_sniper_back_rush_2_complete%\r\n",
                "35d683dcd5015d08a7df6f2b2d62e6a4976642d4edaae34b89edb1c2d9ccd5c1"),
            Patch("gamedata/configs/misc/tm_hospital.ltx",
                "on_reversed = %+hosp_task_sniper_back_rush_3_complete%\r\n",
                ";on_reversed = %+hosp_task_sniper_back_rush_3_complete%\r\n",
                "35d683dcd5015d08a7df6f2b2d62e6a4976642d4edaae34b89edb1c2d9ccd5c1"),
            Patch("gamedata/configs/misc/tm_hospital.ltx",
                "on_reversed = %+hosp_task_sniper_back_rush_4_complete%\r\n",
                ";on_reversed = %+hosp_task_sniper_back_rush_4_complete%\r\n",
                "35d683dcd5015d08a7df6f2b2d62e6a4976642d4edaae34b89edb1c2d9ccd5c1")),
        SrpFix(
            "cs.ai.limansk-sniper-heal-once",
            "Restore the Limansk sniper's health once on retreat",
            "The scripted medic transition restores health on the subsequent logic update rather than once when entering the retreat state.",
            "Moves the one-shot restore action to the guarded transition and removes the repeated state action, as documented beside the upstream change.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/limansk/lim_smart_terrain_6_minigun2.ltx",
                "on_info = {=health_le(0.7) =dist_to_actor_ge(15)} remark@medic_work2\r\n",
                "on_info = {=health_le(0.7) =dist_to_actor_ge(15)} remark@medic_work2 %=restore_health%\r\n",
                "84765c428e7be0801ca65ff5431f80748b98afd2d0cfd18915729bd7ec04b646"),
            Patch("gamedata/configs/scripts/limansk/lim_smart_terrain_6_minigun2.ltx",
                "on_info = %=restore_health%", "",
                "84765c428e7be0801ca65ff5431f80748b98afd2d0cfd18915729bd7ec04b646")),
        SrpFix(
            "cs.ai.hospital-minigunner-danger-keys",
            "Correct the hospital minigunner danger-distance keys",
            "Four danger settings contain a space inside the key name and are therefore ignored by the LTX reader.",
            "Corrects the four key names while preserving their values.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/katacomb_hospital/kat_hosp_z1_minigunner.ltx",
                "ignore_ distance_grenade = 0\r\n", "ignore_distance_grenade = 0\r\n",
                "6e4c3319b2a2c82ce9657a927ced06890dfda023e3b2cc085ff12e86d4afeef8"),
            Patch("gamedata/configs/scripts/katacomb_hospital/kat_hosp_z1_minigunner.ltx",
                "ignore_ distance_corpse = 0\r\n", "ignore_distance_corpse = 0\r\n",
                "6e4c3319b2a2c82ce9657a927ced06890dfda023e3b2cc085ff12e86d4afeef8"),
            Patch("gamedata/configs/scripts/katacomb_hospital/kat_hosp_z1_minigunner.ltx",
                "ignore_ distance_hit = 0\r\n", "ignore_distance_hit = 0\r\n",
                "6e4c3319b2a2c82ce9657a927ced06890dfda023e3b2cc085ff12e86d4afeef8"),
            Patch("gamedata/configs/scripts/katacomb_hospital/kat_hosp_z1_minigunner.ltx",
                "ignore_ distance_sound = 0", "ignore_distance_sound = 0",
                "6e4c3319b2a2c82ce9657a927ced06890dfda023e3b2cc085ff12e86d4afeef8")),
        SrpFix(
            "cs.logic.yantar-zombie-28-section",
            "Make Yantar zombie 28 logic section parseable",
            "The file starts with `[logic]r`, which does not name the logic section expected by the script reader.",
            "Removes the stray trailing character in the section header.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/yantar/yan_zombie_28.ltx",
                "[logic]r\r\n", "[logic]\r\n",
                "a6bfc074d97529a14b85b3b224019156c8f58229e67a68ce284a8790da286bba")),
        SrpFix(
            "cs.dialog.escape-2-level-changers",
            "Keep Escape level changers closed during the PDA assembly",
            "The Escape PDA conversation can be interrupted by entering its active level changers before the sound sequence ends.",
            "Disables the two involved changers for the conversation and restores them at the sound-end signal.",
            GameFixCategory.Community,
            Patch("gamedata/configs/scripts/escape/esc_pda_dialog_2.ltx",
                "on_info = {=actor_in_zone(esc_stalkers_dialog_zone_2)} %=play_sound(esc_stalker_assemble_2_1:stalker:esc_leader_stalkerbase_name)% sr_idle@4s\r\n",
                "on_info = {=actor_in_zone(esc_stalkers_dialog_zone_2)} %=play_sound(esc_stalker_assemble_2_1:stalker:esc_leader_stalkerbase_name) =disable_level_changer(443:tips_wait_conversation_finish) =disable_level_changer(445:tips_wait_conversation_finish)% sr_idle@4s\r\n",
                "d00c93511a0e2ca00e8e8855a1241f6ea2d25ec6dccf7ee3de2d0bfa0f9e741b"),
            Patch("gamedata/configs/scripts/escape/esc_pda_dialog_2.ltx",
                "[sr_idle@7]\r\n",
                "[sr_idle@7]\r\non_signal = sound_end | nil %=enable_level_changer(443) =enable_level_changer(445)%\r\n",
                "d00c93511a0e2ca00e8e8855a1241f6ea2d25ec6dccf7ee3de2d0bfa0f9e741b")),
        SrpFix(
            "cs.dialog.escape-4-level-changer",
            "Keep the Escape level changer closed during the PDA assembly",
            "The Escape PDA conversation can be interrupted by entering its active level changer before the sound sequence ends.",
            "Disables the involved changer for the conversation and restores it at the sound-end signal.",
            GameFixCategory.Community,
            Patch("gamedata/configs/scripts/escape/esc_pda_dialog_4.ltx",
                "on_info = {=actor_in_zone(esc_stalkers_dialog_zone_4)} %=play_sound(esc_stalker_assemble_4_1:stalker:esc_leader_stalkerbase_name)% sr_idle@12s\r\n",
                "on_info = {=actor_in_zone(esc_stalkers_dialog_zone_4)} %=play_sound(esc_stalker_assemble_4_1:stalker:esc_leader_stalkerbase_name) =disable_level_changer(444:tips_wait_conversation_finish)% sr_idle@12s\r\n",
                "581337fc5d515a26e952b9050ebc424d3e9b6a491b2acd79952d34c67f020bc4"),
            Patch("gamedata/configs/scripts/escape/esc_pda_dialog_4.ltx",
                "[sr_idle@14]\r\n",
                "[sr_idle@14]\r\non_signal = sound_end | nil %=enable_level_changer(444)%\r\n",
                "581337fc5d515a26e952b9050ebc424d3e9b6a491b2acd79952d34c67f020bc4")),
        SrpFix(
            "cs.quest.verified-hospital-sniper-danger-keys",
            "Correct the hospital sniper danger-distance key",
            "A misspelled danger-distance key is ignored by the LTX reader.",
            "Corrects both occurrences of the grenade-distance key in the scripted hospital sniper behavior.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/katacomb_hospital/kat_hosp_z1_sniper.ltx",
                "[danger_condition]\r\nignore_distance_corpse = 0\r\nignore_distance_sound = 0\r\nignore_ distance_grenade = 0\r\n",
                "[danger_condition]\r\nignore_distance_corpse = 0\r\nignore_distance_sound = 0\r\nignore_distance_grenade = 0\r\n",
                "23b04b5f51ed63021974f5374d86be1cf0585faee1dda424cc10d1b7d23ece57"),
            Patch("gamedata/configs/scripts/katacomb_hospital/kat_hosp_z1_sniper.ltx",
                "[danger_condition@2]\r\nignore_distance = 0\r\nignore_distance_corpse = 0\r\nignore_distance_sound = 0\r\nignore_ distance_grenade = 0\r\n",
                "[danger_condition@2]\r\nignore_distance = 0\r\nignore_distance_corpse = 0\r\nignore_distance_sound = 0\r\nignore_distance_grenade = 0\r\n",
                "23b04b5f51ed63021974f5374d86be1cf0585faee1dda424cc10d1b7d23ece57")),
        ZrpFix(
            "soc.dialog.wounded-enemy-crash",
            "Prevent wounded-enemy dialog crashes",
            "The wounded-NPC dialog manager can select a help line for normally hostile communities without a matching dialog section.",
            "Adds the four community-specific dialog-manager entries and their English strings from ZRP; it does not replace the dialog manager or Lua scripts.",
            GameFixCategory.Essential,
            Patch("gamedata/config/misc/dialog_manager.ltx",
                "dm_intro_help_12\r\n",
                "dm_intro_help_16\r\ndm_intro_help_15\r\ndm_intro_help_14\r\ndm_intro_help_13\r\ndm_intro_help_12\r\n",
                "d24280998f92802fcc016a120efeaefc0f343ac05131c19e1fb3f15b896ddef4"),
            Patch("gamedata/config/misc/dialog_manager.ltx",
                "[dm_intro_help_2]\r\n",
                "[dm_intro_help_13]\r\nwounded = true\r\nnpc_community = killer\r\ncategory = intro\r\n\r\n[dm_intro_help_14]\r\nwounded = true\r\nnpc_community = bandit\r\ncategory = intro\r\n\r\n[dm_intro_help_15]\r\nwounded = true\r\nnpc_community = monolith\r\ncategory = intro\r\n\r\n[dm_intro_help_16]\r\nwounded = true\r\nnpc_community = military\r\ncategory = intro\r\n\r\n[dm_intro_help_2]\r\n",
                "d24280998f92802fcc016a120efeaefc0f343ac05131c19e1fb3f15b896ddef4"),
            Patch("gamedata/config/text/eng/stable_dialog_manager.xml",
                "\t<string id=\"dm_intro_help_2\">",
                "\t<string id=\"dm_intro_help_13\">\r\n\t\t<text>Can you spare a medkit?</text>\r\n\t</string>\r\n\t<string id=\"dm_intro_help_14\">\r\n\t\t<text>It hurts! Stop the pain!</text>\r\n\t</string>\r\n\t<string id=\"dm_intro_help_15\">\r\n\t\t<text>By the Monolith, help this brother!</text>\r\n\t</string>\r\n\t<string id=\"dm_intro_help_16\">\r\n\t\t<text>Comrade! I need help...</text>\r\n\t</string>\r\n\t<string id=\"dm_intro_help_2\">",
                "163ce72636007fde27f468d3868fcdc6e665a39bb70e573a168fbbd6d7ba858e")),
        ZrpFix(
            "soc.dialog.yurik-options-out-of-order",
            "Keep Yurik's dialog options available",
            "One Yurik conversation branch is gated by the wrong info-portion, so taking options in another order can make the remaining conversation disappear.",
            "Changes only the faulty guard in the garbage novice dialog to the info-portion used by that branch.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/gameplay/dialogs_garbage.xml",
                "<dont_has_info>gar_add_fake_spot3</dont_has_info>",
                "<dont_has_info>gar_add_fake_spot1</dont_has_info>",
                "baf38c4e00959e211c1ca708ebe40e949c37ac4833b154bdff04fbdf1cad0254")),
        ZrpFix(
            "soc.quest.kruglov-rescue-dialog-recovery",
            "Recover Kruglov's stalled rescue conversation",
            "If Kruglov stalls during the Rostok rescue, talking to him again does not reset the assigned gulag job.",
            "Adds the upstream job reset action to the existing rescue follow-up phrase.",
            GameFixCategory.Essential,
            Patch("gamedata/config/gameplay/dialogs_bar.xml",
                "<text>bar_ecolog_crush_professor_start_91</text>\r\n",
                "<text>bar_ecolog_crush_professor_start_91</text>\r\n                <action>xr_gulag.resetJob</action>\r\n",
                "0556ce86262eed32d68c602d2f731c0be57ef7355d699492907fee4d3f0cc159")),
        ZrpFix(
            "soc.quest.skull-lukash-task-after-attack",
            "Let Skull complete the Lukash elimination task after the attack starts",
            "The silent Skull-dialog completion branch is disabled as soon as the delayed Freedom-base attack begins, even when the task has already reached its completion state.",
            "Replaces only the obsolete no-auto-attack guard with the task-issued info-portion check documented by ZRP.",
            GameFixCategory.Essential,
            Patch("gamedata/config/gameplay/dialogs_military.xml",
                "            <phrase id=\"2\">\r\n                <text />\r\n                <dont_has_info>mil_dolg_auto_attack</dont_has_info>\r\n                <dont_has_info>mil_dolg_gulag_free</dont_has_info>\r\n                <has_info>mil_sniper_dead</has_info>\r\n                <has_info>mil_lukash_dead</has_info>\r\n                <next>200</next>\r\n            </phrase>",
                "            <phrase id=\"2\">\r\n                <text />\r\n                <!-- <dont_has_info>mil_dolg_auto_attack</dont_has_info> -->\r\n                <has_info>mil_dolg_final_task</has_info>\r\n                <dont_has_info>mil_dolg_gulag_free</dont_has_info>\r\n                <has_info>mil_sniper_dead</has_info>\r\n                <has_info>mil_lukash_dead</has_info>\r\n                <next>200</next>\r\n            </phrase>",
                "58d97d0348e275a10a9a0973c7fa3db361abde8632e981bb0cc4a8e2e2ced73c")),
        ZrpFix(
            "soc.quest.yantar-secret-tunnel-marker",
            "Hide the Yantar tunnel exit until the route is discovered",
            "The secret tunnel exit marker is visible on the PDA before the player learns about the route.",
            "Adds the tunnel-start task gate and the engine's hidden-marker flag while preserving the existing completion condition.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/gameplay/tasks_yantar.xml",
                "\t\t<objective>\r\n\t\t\t<text>yan_secret_tonnel</text>\r\n\t\t\t<map_location_type>green_location</map_location_type>\r\n\t\t\t<object_story_id>yan_secret_exit</object_story_id>\r\n\t\t\t<infoportion_complete>yantar_tunnel_finish</infoportion_complete>\r\n\t\t</objective>",
                "\t\t<objective>\r\n\t\t\t<text>yan_kill_brain_task_2</text>\r\n\t\t\t<infoportion_complete>yantar_tunnel_start</infoportion_complete>\r\n\t\t</objective>\r\n\t\t<objective>\r\n\t\t\t<text>yan_secret_tonnel</text>\r\n\t\t\t<map_location_type hint=\"yan_secret_tonnel\">green_location</map_location_type>\r\n\t\t\t<object_story_id>yan_secret_exit</object_story_id>\r\n\t\t\t<map_location_hidden>1</map_location_hidden> \r\n\t\t\t<infoportion_complete>yantar_tunnel_finish</infoportion_complete>\r\n\t\t</objective>",
                "9135738b924d78f0e14052d31abb533a472d905f9c987e4beb421bdad5c64b2b")),
        ZrpFix(
            "soc.quest.dark-valley-sacrifice-guard-release",
            "Release Dark Valley executioners when the victim is already dead",
            "The sacrifice guards have no exit from their active role when the victim dies before their scripted sequence finishes.",
            "Adds the existing victim-dead info-portion exit to both executioner states; it does not change the sacrifice spawn or victim state.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/scripts/val_sacrifice_guard1.ltx",
                "on_info                     = {+val_sacrifice_victim_phrase1_end} remark@val_sacrifice_guard1_phrase1\r\n",
                "on_info                     = {+val_sacrifice_victim_phrase1_end} remark@val_sacrifice_guard1_phrase1\r\non_info2                    = {+val_sacrifice_victim_dead} %+val_sacrifice_finish%\r\n",
                "c48d1832d9a63e18f1ff4478dee9c15f73eed8a40629fb6e4e897ab051df6ff8"),
            Patch("gamedata/config/scripts/val_sacrifice_guard2.ltx",
                "on_info                     = {+val_sacrifice_guard1_phrase1_end} remark@val_sacrifice_guard2_phrase1\r\n",
                "on_info                     = {+val_sacrifice_guard1_phrase1_end} remark@val_sacrifice_guard2_phrase1\r\non_info2                    = {+val_sacrifice_victim_dead} %+val_sacrifice_finish%\r\n",
                "7c73df7da02df7f9d98980c40c6eea110b194d4dba36a0e8948f2d1f77f202cb")),
        ZrpFix(
            "soc.quest.petruha-report-once",
            "Prevent Petruha's team from repeating its report",
            "Petruha's backup team can return to the wrong camp state after reporting that he died, causing the report logic to run again.",
            "Corrects the two state transitions that must stay within the second camp's report path and preserve its sent-info guard.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/misc/gulag_escape.ltx",
                "on_info = {+esc_petruha_die -esc_petruha_report2 -esc_report_send} remark@esc_assault_home1\r\n",
                "on_info = {+esc_petruha_die -esc_petruha_report2 -esc_report_send} remark@esc_assault_home2\r\n",
                "b84dc3809d329bb5eafb391ee9e09c5f3fd8e96465ac01e2e8bf4b772883ab5d"),
            Patch("gamedata/config/misc/gulag_escape.ltx",
                "[remark@esc_assault_home22]\r\npath_walk = escape_factory_return_path\r\nanim = guard_rac\r\nsnd = esc_petruha_raport\r\non_signal = sound_end| kamp@esc_assault_home1 %+esc_report_send%\r\n",
                "[remark@esc_assault_home22]\r\npath_walk = escape_factory_return_path\r\nanim = guard_rac\r\nsnd = esc_petruha_raport\r\non_signal = sound_end| kamp@esc_assault_home2 %+esc_report_send%\r\n",
                "b84dc3809d329bb5eafb391ee9e09c5f3fd8e96465ac01e2e8bf4b772883ab5d")),
        ZrpFix(
            "soc.logic.freedom-trader-armory-meet-schemes",
            "Restore Freedom trader and armory guard interactions",
            "The trader's meet section name does not match its reference, the armory guard's weapon-state key is misspelled, and several Army Warehouses meet schemes use the unsupported on_meet name.",
            "Applies the named ZRP section and key corrections in this file only; it leaves the trader's schedules, rewards, and faction behavior unchanged.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "[meet@mil_freedrader]\r\n", "[meet@mil_freedom_trader]\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "meet_sate_wpn = 2|backoff@threat_back\r\n", "meet_state_wpn = 2|backoff@threat_back\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "meet = on_meet@mil_freedom_guard1\r\n", "meet = meet@mil_freedom_guard1\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "[on_meet@mil_freedom_guard1]\r\n", "[meet@mil_freedom_guard1]\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "[on_meet@mil_freedom_max]\r\n", "[meet@mil_freedom_max]\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "meet = on_meet@mil_freedom_max\r\n", "meet = meet@mil_freedom_max\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "[on_meet@mil_freedom_stalker4]\r\n", "[meet@mil_freedom_stalker4]\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "meet = on_meet@mil_freedom_stalker4\r\n", "meet = meet@mil_freedom_stalker4\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "[on_meet@mil_freedom_stalker5]\r\n", "[meet@mil_freedom_stalker5]\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a"),
            Patch("gamedata/config/misc/gulag_mil_freedom1.ltx", "meet = on_meet@mil_freedom_stalker5\r\n", "meet = meet@mil_freedom_stalker5\r\n", "42aa4baf3831d03d243434cc59555c0ae95fd6ecf26fb8176dcdac690956e44a")),
        ZrpFix(
            "soc.logic.freedom-blockpost-meet-scheme",
            "Restore the Freedom blockpost commander meet scheme",
            "The commander references an on_meet scheme that is not recognized as the meet scheme declared by the game logic.",
            "Renames the referenced scheme and its matching section without changing any dialogue conditions.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/misc/gulag_mil_fblockpost.ltx", "meet = on_meet@mil_fblockpost_commander\r\n", "meet = meet@mil_fblockpost_commander\r\n", "b9c839fdad4df50ef67014671b0fc0d17a3f6ce447be3d955da66924212a23a0"),
            Patch("gamedata/config/misc/gulag_mil_fblockpost.ltx", "[on_meet@mil_fblockpost_commander]\r\n", "[meet@mil_fblockpost_commander]\r\n", "b9c839fdad4df50ef67014671b0fc0d17a3f6ce447be3d955da66924212a23a0")),
        ZrpFix(
            "soc.logic.freedom-max-attack-meet-scheme",
            "Restore the Freedom attack leader's meet scheme",
            "The leader of the Army Warehouses attack references an on_meet section instead of the supported meet scheme.",
            "Renames only the matching section and reference documented in the ZRP Army Warehouses logic fix.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/misc/gulag_mil_freedom3.ltx", "meet = on_meet@mil_freedom_max_attack\r\n", "meet = meet@mil_freedom_max_attack\r\n", "f8e90b693208e888efab1dbf3c2c23aa3f68bd21a504721aaf5e97410c3c73a3"),
            Patch("gamedata/config/misc/gulag_mil_freedom3.ltx", "[on_meet@mil_freedom_max_attack]\r\n", "[meet@mil_freedom_max_attack]\r\n", "f8e90b693208e888efab1dbf3c2c23aa3f68bd21a504721aaf5e97410c3c73a3")),
        ZrpFix(
            "soc.logic.red-forest-combat-and-death-schemes",
            "Repair the Red Forest fight and death scheme references",
            "The Radar faction jobs route NPC deaths through a hit scheme, and the Monolith combat block uses a section name that is not a combat scheme.",
            "Points each faction job's death callback at the shipped death section and names the Monolith block as a combat scheme, with all anchors limited to those exact logic sections.",
            GameFixCategory.Recommended,
            RadarDeathPatch("rad_svoboda", "walker@rad_svoboda"),
            RadarDeathPatch("rad_svoboda1", "walker@rad_svoboda1"),
            RadarDeathPatch("rad_svoboda2", "walker@rad_svoboda2"),
            RadarDeathPatch("rad_svoboda3", "walker@rad_svoboda3"),
            RadarDeathPatch("rad_svoboda4", "walker@rad_svoboda4"),
            RadarDeathPatch("rad_svoboda5", "walker@rad_svoboda5"),
            RadarDeathPatch("rad_dolg", "walker@rad_dolg"),
            RadarDeathPatch("rad_dolg1", "walker@rad_dolg1"),
            RadarDeathPatch("rad_dolg2", "walker@rad_dolg2"),
            RadarDeathPatch("rad_dolg3", "walker@rad_dolg3"),
            RadarDeathPatch("rad_dolg4", "walker@rad_dolg4"),
            RadarDeathPatch("rad_dolg5", "walker@rad_dolg5"),
            Patch("gamedata/config/misc/gulag_radar.ltx", "[rad_monolith]\r\n", "[combat@rad_monolith]\r\n", "f4f86dab8e31df2b46e0589854e3cbb2f60ace2c15eaab895acebfad7af62fc0")),
        ZrpFix(
            "soc.config.red-forest-stash-item-assignment",
            "Repair the Red Forest Kolobok stash item list",
            "One stash's item list contains an extra assignment operator, making its LTX item sequence malformed.",
            "Removes only the duplicate equals sign from the affected stash entry.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/misc/treasure_manager.ltx", "items =  = af_fuzz_kolobok, ammo_m209, 5\r\n", "items = af_fuzz_kolobok, ammo_m209, 5\r\n", "3a69d02dd81698a17b1da180e8834b49f70f27b638de9557cd040270d16c0d96")),
        ZrpFix(
            "soc.config.bar-ecologist-guard-class",
            "Correct the Bar ecologist guard class reference",
            "The Bar ecologist guard points to a class name with incorrect capitalization, so the reference does not resolve to the defined NPC class.",
            "Corrects the one character-class token in the retail description file.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/gameplay/character_desc_bar.xml", "<class>bar_Ecolog_guard</class>", "<class>bar_ecolog_guard</class>", "b51c145ebec57935914472ea8f5b6dd4c476d980d458711ef6acf4d5f8d5ae27")),
        ZrpFix(
            "soc.quest.freedom-reward-relation-syntax",
            "Correct malformed Freedom task relationship entries",
            "Two Freedom quest reward entries omit the separator before the faction relation value, so the intended relationship reward is malformed.",
            "Adds the missing delimiter to only the two documented reward entries; other reward and balance values stay untouched.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/misc/task_manager.ltx", "reward_relation = dolg, -100, freedom +150\r\n", "reward_relation = dolg, -100, freedom, +150\r\n", "88baa94bf4254bb59f6c68d5d7aa416b4557446bee53243114298758ab44145b"),
            Patch("gamedata/config/misc/task_manager.ltx", "reward_relation = freedom +50\r\n", "reward_relation = freedom, +50\r\n", "88baa94bf4254bb59f6c68d5d7aa416b4557446bee53243114298758ab44145b")),
        ZrpFix(
            "soc.logic.bar-danger-hit-distance-key",
            "Correct the Bar gulag hit-distance key",
            "The ecologist job uses an unrecognized danger-distance key, so its configured hit-response distance is ignored.",
            "Renames the key to the supported ignore_distance_hit field in its one affected section.",
            GameFixCategory.Recommended,
            Patch("gamedata/config/misc/gulag_bar.ltx", "ignore_distance_danger_hit     = 0\r\n", "ignore_distance_hit     = 0\r\n", "358b61119988508e038cddc1d3314e8bfb46002cacf0ae28dfdad1e918c66fb2")),
        CopFix(
            "cop.weapon.f1-blast-radius",
            "Match F1 blast radius to its documented effect",
            "The community patch changes the F1 blast strength and radius to match the grenade's intended explosive effect; this is a gameplay balance change.",
            "Applies only the two blast values from the upstream weapon file. It is Community-only and excluded from presets.",
            GameFixCategory.Community,
            Patch("gamedata/configs/weapons/w_f1.ltx", "blast\t\t\t\t\t= 3", "blast\t\t\t\t\t= 5", "510a6432c214b863e2a04a5be54e8a4fad8fea47d61be8464e32329a282fb913"),
            Patch("gamedata/configs/weapons/w_f1.ltx", "blast_r\t\t\t\t\t= 5", "blast_r\t\t\t\t\t= 7", "510a6432c214b863e2a04a5be54e8a4fad8fea47d61be8464e32329a282fb913")),
        CopFix(
            "cop.weapon.rgd5-blast-radius",
            "Match RGD-5 blast strength to its documented effect",
            "The community patch raises the RGD-5 blast value; this changes weapon balance rather than repairing a demonstrated progression or stability fault.",
            "Applies only the single upstream blast value and remains Community-only, outside presets.",
            GameFixCategory.Community,
            Patch("gamedata/configs/weapons/w_rgd5.ltx", "blast\t\t\t\t\t= 1.5", "blast\t\t\t\t\t= 2.5", "ca2cc2e0d9c6c7330e234be07a218449f903b18d70f40c48d908c83926903fe7")),
        CopFix(
            "cop.weapon.spas12-sight-alignment",
            "Align the SPAS-12 ironsight and scope offsets",
            "The upstream patch moves the SPAS-12 aiming offsets in both aspect-ratio layouts; the retail positions leave the sight picture misaligned.",
            "Changes only the four aiming position and rotation values. It does not copy the upstream file's unrelated whitespace edits.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/weapons/w_spas12.ltx", "aim_hud_offset_pos\t\t\t\t= -0.098000,0.051000,0.000000", "aim_hud_offset_pos\t\t\t\t= -0.097600, 0.090200, 0.050000", "c4ae9a3eaf0a397a8599fc37ca0b445842427c628aeb89eabd4cf0accb7039bf"),
            Patch("gamedata/configs/weapons/w_spas12.ltx", "aim_hud_offset_rot\t\t\t\t= 0.017500,0.025000,-0.022500", "aim_hud_offset_rot\t\t\t\t=  0.051000, 0.025000,-0.022500", "c4ae9a3eaf0a397a8599fc37ca0b445842427c628aeb89eabd4cf0accb7039bf"),
            Patch("gamedata/configs/weapons/w_spas12.ltx", "aim_hud_offset_pos_16x9\t\t\t\t= -0.107500,0.119000,0.000000", "aim_hud_offset_pos_16x9\t\t\t= -0.106600, 0.158000, 0.050000", "c4ae9a3eaf0a397a8599fc37ca0b445842427c628aeb89eabd4cf0accb7039bf"),
            Patch("gamedata/configs/weapons/w_spas12.ltx", "aim_hud_offset_rot_16x9\t\t\t\t= 0.052500,0.045000,-0.045000", "aim_hud_offset_rot_16x9\t\t\t=  0.087000, 0.046500,-0.045000", "c4ae9a3eaf0a397a8599fc37ca0b445842427c628aeb89eabd4cf0accb7039bf")),
        CopFix(
            "cop.weapon.val-sight-alignment",
            "Align and de-duplicate the AS Val sight offsets",
            "The retail HUD section contains two competing 16:9 aiming offset pairs, while the patch supplies one corrected pair and adjusts the standard layout.",
            "Replaces the two standard layout values, replaces the first 16:9 pair, and removes only the duplicate second pair.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/weapons/w_val.ltx", "aim_hud_offset_pos_16x9\t\t\t\t= -0.110000,0.048500,-0.018000", "aim_hud_offset_pos_16x9\t\t= -0.137500, 0.079800,-0.020000", "386df00dfdbc4a9ae14aa56dc66a5348b0a1e863dfbc34d7b2f32f7a39eb8e6f"),
            Patch("gamedata/configs/weapons/w_val.ltx", "aim_hud_offset_rot_16x9\t\t\t\t= 0.017500,0.005000,-0.027500", "aim_hud_offset_rot_16x9\t\t=  0.017800, 0.020850,-0.040000", "386df00dfdbc4a9ae14aa56dc66a5348b0a1e863dfbc34d7b2f32f7a39eb8e6f"),
            Patch("gamedata/configs/weapons/w_val.ltx", "aim_hud_offset_pos\t\t\t\t= -0.109500,0.041000,-0.035500", "aim_hud_offset_pos\t\t= -0.108900, 0.044200,-0.035500", "386df00dfdbc4a9ae14aa56dc66a5348b0a1e863dfbc34d7b2f32f7a39eb8e6f"),
            Patch("gamedata/configs/weapons/w_val.ltx", "aim_hud_offset_rot\t\t\t\t= -0.017500,-0.042500,-0.022500", "aim_hud_offset_rot\t\t= -0.018500,-0.043200,-0.022500", "386df00dfdbc4a9ae14aa56dc66a5348b0a1e863dfbc34d7b2f32f7a39eb8e6f"),
            Patch("gamedata/configs/weapons/w_val.ltx", "aim_hud_offset_pos_16x9\t\t\t\t= -0.143000,0.068500,-0.018000\r\n", string.Empty, "386df00dfdbc4a9ae14aa56dc66a5348b0a1e863dfbc34d7b2f32f7a39eb8e6f"),
            Patch("gamedata/configs/weapons/w_val.ltx", "aim_hud_offset_rot_16x9\t\t\t\t= 0.012500,0.020000,-0.010000\r\n", string.Empty, "386df00dfdbc4a9ae14aa56dc66a5348b0a1e863dfbc34d7b2f32f7a39eb8e6f")),
        CopFix(
            "cop.dialog.correct-anomaly-name",
            "Use the correct name for the Claw anomaly field",
            "The Skadovsk dialogue labels the gravitational anomaly field as Claw's namesake `Fang`, while the game location is Claw.",
            "Corrects one Russian dialogue string ID; no quest state, map marker or world data changes.",
            GameFixCategory.Recommended,
            CopTextPatch("gamedata/configs/text/rus/st_dialog_manager.xml", "dm_anomalies_9",
                "Если интересуют гравитационные артефакты, то надо в аномалии «Клык» искать. Это место не заметить сложно - там аномалиями сильно землю покорёжило, часть холма просто начисто снесло. А в пещерах, которые в холме открылись, сразу же снорки обосновались, но наружу они редко выходят.",
                "Если интересуют гравитационные артефакты, то надо в аномалии «Коготь» искать. Это место не заметить сложно - там аномалиями сильно землю покорёжило, часть холма просто начисто снесло. А в пещерах, которые в холме открылись, сразу же снорки обосновались, но наружу они редко выходят.",
                "b3f1e7b732759d67b3794ebd6571f85022f0c7a575e92fb52092af89e69abd26")),
        CopFix(
            "cop.quest.memory-module-unlock-attribution",
            "Avoid crediting Novikov when Azot unlocks the memory module",
            "The quest item description credits Novikov even when Azot performs the module unlock, so the text contradicts the player's route.",
            "Replaces the fixed name with the source patch's neutral attribution in this single item description.",
            GameFixCategory.Recommended,
            CopTextPatch("gamedata/configs/text/rus/st_items_quest.xml", "st_jup_b10_ufo_memory_2_desc",
                "Модуль памяти, извлечённый из беспилотного разведывательного аппарата. Новиков разблокировал модуль, открыв доступ к информации, которая была собрана разведчиком: среди прочего в ней содержатся пеленги на три радиомаяка.",
                "Модуль памяти, извлечённый из беспилотного разведывательного аппарата. Какой-то специалист разблокировал модуль, открыв доступ к информации, которая была собрана разведчиком: среди прочего в ней содержатся пеленги на три радиомаяка.",
                "a087421f6d795211e7c1bd5e5783999e1971560f5036b3ed01cef2294f4455a6")),
        CopFix(
            "cop.dialog.gonta-after-soroka-recovered",
            "Remove the stale Magpie reference from Gonta's chimera invitation",
            "Gonta's invitation still praises the player for finding Soroka after that story point has already been resolved, producing a contradictory repeat dialogue.",
            "Removes only the stale clause from the two corresponding dialogue choices.",
            GameFixCategory.Recommended,
            CopTextPatch("gamedata/configs/text/rus/st_dialogs_zaton.xml", "zat_b106_stalker_gonta_start_12",
                "Постой!.. Мы выследили химеру, дело срочное. Краб ещё не отошёл, Данилы всё нет, а вдвоём на неё идти - ну глупо будет. Ты мужик что надо, Сороку вот нашел. Айда с нами, на химеру поохотиться?",
                "Постой!.. Мы выследили химеру, дело срочное. Краб ещё не отошёл, Данилы всё нет, а вдвоём на неё идти - ну глупо будет. Ты мужик что надо, айда с нами, на химеру поохотиться?",
                "ba45d77dc2d8531a303f3defa54218d3e97aa59a72c9419209d3a62268413bba"),
            CopTextPatch("gamedata/configs/text/rus/st_dialogs_zaton.xml", "zat_b106_stalker_gonta_start_13",
                "Постой!.. Мы выследили химеру, дело срочное. Краб ещё не отошёл, да и Данила... эх!.. Но вдвоём-то на неё идти глупо будет! Ты мужик что надо, Сороку вот нашел. Айда с нами, на химеру поохотиться?",
                "Постой!.. Мы выследили химеру, дело срочное. Краб ещё не отошёл, да и Данила... эх!.. Но вдвоём-то на неё идти глупо будет! Ты мужик что надо, айда с нами, на химеру поохотиться?",
                "ba45d77dc2d8531a303f3defa54218d3e97aa59a72c9419209d3a62268413bba")),
        PrpFix(
            "cop.prp.crow-counter-guard",
            "Guard crow cleanup against duplicate decrements",
            "Repeated network-object cleanup can decrement the crow counter after the crow was already removed.",
            "Removes a crow ID only while it is registered and clamps the counter at zero, using the PRP fix in both cleanup paths.",
            GameFixCategory.Recommended,
            Patch("gamedata/scripts/bind_crow.script",
                "function crow_binder:net_destroy()\r\n    self.object:set_callback(callback.death, nil)\r\n    bind_crow.crow_storage[self.object:id()] = nil\r\n\tbind_crow.crow_counter = bind_crow.crow_counter - 1\r\n",
                "function crow_binder:net_destroy()\r\n    self.object:set_callback(callback.death, nil)\r\n    if (bind_crow.crow_storage[self.object:id()] ~= nil) then --*Crow FIX*\r\n        bind_crow.crow_storage[self.object:id()] = nil\r\n        bind_crow.crow_counter = bind_crow.crow_counter - 1\r\n        if (bind_crow.crow_counter < 0) then --*Crow FIX*\r\n            bind_crow.crow_counter = 0 --*Crow FIX*\r\n        end --*Crow FIX*\r\n    end --*Crow FIX*\r\n",
                "45ffda2c2d293192bcb86dde3d79336eebda0b9ed5b0f073467bab43f88d4688"),
            Patch("gamedata/scripts/bind_crow.script",
                "function crow_binder:death_callback(victim, who)\r\n    self.body_timer = time_global()\r\n    bind_crow.crow_storage[self.object:id()] = nil\r\n\tbind_crow.crow_counter = bind_crow.crow_counter - 1\r\n",
                "function crow_binder:death_callback(victim, who)\r\n    self.body_timer = time_global()\r\n    if (bind_crow.crow_storage[self.object:id()] ~= nil) then --*Crow FIX*\r\n        bind_crow.crow_storage[self.object:id()] = nil\r\n        bind_crow.crow_counter = bind_crow.crow_counter - 1\r\n        if (bind_crow.crow_counter < 0) then --*Crow FIX*\r\n            bind_crow.crow_counter = 0 --*Crow FIX*\r\n        end --*Crow FIX*\r\n    end --*Crow FIX*\r\n",
                "45ffda2c2d293192bcb86dde3d79336eebda0b9ed5b0f073467bab43f88d4688")),
        PrpFix(
            "cop.prp.x8-burer-health-guard",
            "Remove the X8 burer hit-triggered full heal",
            "Each X8 burer restores its full health when hit while the actor is outside the lab's outer restriction.",
            "Removes the three matching on-hit callbacks and their restore-health states from the X8 burer logic file.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/labx8/lx8_burers.ltx", "on_hit = hit_1\r\n", string.Empty, "acac8a1b517981293b6764cd5462317fea4afb54aa37c6adf959198297ede8de"),
            Patch("gamedata/configs/scripts/labx8/lx8_burers.ltx", "[hit_1]\r\non_info = {=hit_by_actor !actor_in_zone(lx8_sr_burer_out_restr)} %=restore_health% \r\n", string.Empty, "acac8a1b517981293b6764cd5462317fea4afb54aa37c6adf959198297ede8de"),
            Patch("gamedata/configs/scripts/labx8/lx8_burers.ltx", "on_hit = hit_2\r\n", string.Empty, "acac8a1b517981293b6764cd5462317fea4afb54aa37c6adf959198297ede8de"),
            Patch("gamedata/configs/scripts/labx8/lx8_burers.ltx", "[hit_2]\r\non_info = {=hit_by_actor !actor_in_zone(lx8_sr_burer_out_restr)} %=restore_health% \r\n", string.Empty, "acac8a1b517981293b6764cd5462317fea4afb54aa37c6adf959198297ede8de"),
            Patch("gamedata/configs/scripts/labx8/lx8_burers.ltx", "on_hit = hit_3\r\n", string.Empty, "acac8a1b517981293b6764cd5462317fea4afb54aa37c6adf959198297ede8de"),
            Patch("gamedata/configs/scripts/labx8/lx8_burers.ltx", "[hit_3]\r\non_info = {=hit_by_actor !actor_in_zone(lx8_sr_burer_out_restr)} %=restore_health% ", string.Empty, "acac8a1b517981293b6764cd5462317fea4afb54aa37c6adf959198297ede8de")),
        PrpFix(
            "cop.prp.jupiter-scanner-task-guard",
            "Require the Jupiter scanner task before placing the extra scanners",
            "The fourth and fifth Jupiter scanner fields can prompt placement before the scanner task has started.",
            "Adds the task-start info-portion to only the two additional scanner triggers.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/jupiter/jup_b32_sr_scanners.ltx",
                "on_info5 = {=actor_in_zone(jup_b32_sr_scanner_place_4) -jup_b32_scanner_4_placed} sr_idle@place %=run_tutorial(jup_b32_scanner)%\r\n",
                "on_info5 = {=actor_in_zone(jup_b32_sr_scanner_place_4) -jup_b32_scanner_4_placed +jup_b32_task_addon_start} sr_idle@place %=run_tutorial(jup_b32_scanner)%\r\n",
                "5e76767ec1a869adc6ea143c58e0a1302de2e7a343d35ce7e67aa51adbaa0a4c"),
            Patch("gamedata/configs/scripts/jupiter/jup_b32_sr_scanners.ltx",
                "on_info6 = {=actor_in_zone(jup_b32_sr_scanner_place_5) -jup_b32_scanner_5_placed} sr_idle@place %=run_tutorial(jup_b32_scanner)%\r\n",
                "on_info6 = {=actor_in_zone(jup_b32_sr_scanner_place_5) -jup_b32_scanner_5_placed +jup_b32_task_addon_start} sr_idle@place %=run_tutorial(jup_b32_scanner)%\r\n",
                "5e76767ec1a869adc6ea143c58e0a1302de2e7a343d35ce7e67aa51adbaa0a4c")),
        PrpFix(
            "cop.prp.altered-insulator-door-gate",
            "Gate the altered-insulator door on task state and artifact possession",
            "The door's zone trigger enters its open state without checking the associated task or the half-artifact.",
            "Adds the existing task-start flag and required artifact predicate to the single door transition.",
            GameFixCategory.Recommended,
            Patch("gamedata/configs/scripts/jupiter/jup_b1_door.ltx",
                "on_info = {=actor_in_zone(jup_b1_open_door_zone)} ph_door@close\r\n",
                "on_info = {=actor_in_zone(jup_b1_open_door_zone) +jup_b1_start =actor_has_item(jup_b1_half_artifact)} ph_door@close\r\n",
                "dc98e408ef1804f2bbf7337b18d60b989ec03452410af7a830e0f9ae9cf93597")),
        PrpFix(
            "cop.prp.knife-hit-reach",
            "Correct the knife's second hit distance and radius",
            "The second knife hit volume is shorter and narrower than the first hit volume.",
            "Changes only the two secondary-hit distance and radius values from the PRP fix.",
            GameFixCategory.Community,
            Patch("gamedata/configs/weapons/w_knife.ltx", "spash2_dist\t\t\t\t= 1\r\n", "spash2_dist\t\t\t\t= 1.2\r\n", "67149d44252f315b85c370a2e99ba6958dc4499a5ecb70971958e0291ec3c687"),
            Patch("gamedata/configs/weapons/w_knife.ltx", "spash2_radius\t\t\t= 0.25\r\n", "spash2_radius\t\t\t= 0.5\r\n", "67149d44252f315b85c370a2e99ba6958dc4499a5ecb70971958e0291ec3c687")),
        PrpFix(
            "cop.prp.sky-stretching-fix",
            "Correct sky stretching in the R2 and R3 sky shaders",
            "The retail sky vertex shaders uniformly scale the vertical position, producing the stretched-sky defect addressed by PRP.",
            "Replaces only the sky-position transform in the DirectX 9 (R2) and DirectX 10 (R3) shader sources.",
            GameFixCategory.Recommended,
            Patch("gamedata/shaders/r2/sky2.vs",
                "\tfloat4\ttpos\t    = mul\t(1000, v.p);\r\n",
                "\t//float4\ttpos\t    = mul\t(1000, v.p);\r\n\tfloat4 tpos = float4(1000*v.p.x, 500*v.p.y, 1000*v.p.z, 1000*v.p.w);\r\n",
                "b69fda89f3ae26fd4371af7a43730f3924a4bfbd4975544a5824d03d5eafc4a9"),
            Patch("gamedata/shaders/r3/sky2.vs",
                "\tfloat4\ttpos\t    = mul\t(1000, v.p);\r\n",
                "\tfloat4 tpos = float4(1000*v.p.x, 500*v.p.y, 1000*v.p.z, 1000*v.p.w);\r\n",
                "7da9bfc937424b420078f3d57af97ae790dd3b4c4340d7c997b70bd6d1634df1")),
        CopFix(
            "cop.localization.dialog-text-corrections",
            "Correct selected Russian dialogue spelling",
            "The Russian dialogue pack contains a spelling error in a player-facing line.",
            "Corrects the exact source-backed verb spelling for one stable dialogue ID.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_dialogs.xml", "about_quests_dialog_bandit_33",
                "Было дело, один пацанчик тёр... Типа шел это он за сталкером, развести того на хабар, а тут - оба-на! - стрельба. Он, короче, пригляделся, а там военные с наёмниками жару один другому дают. Ну, пацанчик залёг от греха, а пока переждал разборку, сталкер уже ноги сделал. От такая засада!",
                "Было дело, один пацанчик тёр... Типа шёл это он за сталкером, развести того на хабар, а тут - оба-на! - стрельба. Он, короче, пригляделся, а там военные с наёмниками жару один другому дают. Ну, пацанчик залёг от греха, а пока переждал разборку, сталкер уже ноги сделал. От такая засада!",
                "0eaa898c8989f733ed5220e4bdd426e99ff5c5e383a988d82339a733b629dfb6")),
        CopFix(
            "cop.localization.jupiter-dialog-spelling",
            "Correct selected Jupiter dialogue spelling",
            "The Russian Jupiter dialogue contains a common homophone spelling error.",
            "Corrects the exact `всё` spelling in one source-backed dialogue ID.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_dialogs_jupiter.xml", "jup_a12_merc_done_dialog_11",
                "Все, сталкер, мы свою долю честно отработали. Пора линять.",
                "Всё, сталкер, мы свою долю честно отработали. Пора линять.",
                "8ca2c1c549a090da1d2853c8c8cdb35ca51f22689fb244c1b35a5e3712bda824")),
        CopFix(
            "cop.localization.pripyat-dialog-spelling",
            "Correct selected Pripyat reward dialogue spelling",
            "The Zulu reward line contains a typo in the imperative verb and omits the standard ё in пулемёт.",
            "Corrects one source-backed dialogue entry without changing the reward or its trigger.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_dialogs_pripyat.xml", "jup_b15_zulus_b301_reward_dialog_0",
                "Погоди... Вот, возми. Самый надёжный пулемет в Зоне!",
                "Погоди... Вот, возьми. Самый надёжный пулемёт в Зоне!",
                "68223ab2ef5f636b5612391b23d542d23200c8eaf6a92d5d99ba83231138d901")),
        CopFix(
            "cop.localization.jupiter-quest-text",
            "Correct selected Jupiter quest text spelling",
            "The hostage objective uses the wrong infinitive form in its Russian title.",
            "Corrects the verb in the single exact quest title string.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_quests_jupiter.xml", "jup_a12_free_prisoner_ransom_name",
                "Заложник: договорится о выкупе Митяя",
                "Заложник: договориться о выкупе Митяя",
                "e0dcbca0d5c9cf7cb46d2e686781e177cb7a254987dfcb3898100d832d7e95c1")),
        CopFix(
            "cop.localization.pripyat-quest-text",
            "Clarify selected Pripyat quest text",
            "The military outpost objective has a missing comma and an awkward plural reference in Russian.",
            "Corrects only the objective sentence in its stable quest string ID.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_quests_pripyat.xml", "pri_a18_go_post_text",
                "Необходимо уничтожить всех «монолитовцев» засевших в здании. Их скопления представляют угрозу для лагеря военных.",
                "Необходимо уничтожить всех «монолитовцев», засевших в здании. Они представляют угрозу для лагеря военных.",
                "b853efbd3e40f08fe080eafa19b8c39c728b8a3324cfb256b8c5da8ea5d0d419")),
        CopFix(
            "cop.localization.zaton-quest-text",
            "Correct selected Zaton quest text spelling",
            "The first Sultan job uses a misspelled Russian verb in its objective description.",
            "Corrects only the source-backed verb in one quest string ID.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_quests_zaton.xml", "zat_b30_sultan_task_1_text",
                "Торговец Сыч считает, что Борода не выполняет условия сделки, и советует обратится за помощью к местному авторитету - Султану.",
                "Торговец Сыч считает, что Борода не выполняет условия сделки, и советует обратиться за помощью к местному авторитету - Султану.",
                "da514789a7528e8c55d8fe2aba29b33356312bfe509cb2aa12d0cd96a537524c")),
        CopFix(
            "cop.localization.weapon-description-correction",
            "Correct selected ammunition description wording",
            "The 5.45×39 mm description redundantly calls out the Warsaw Pact countries as many countries and participants.",
            "Uses the shorter source-backed wording in one item description; ammunition properties are unchanged.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_items_weapons.xml", "ammo-5.45x39-ap_descr",
                "Армейский патрон калибра 5,45x39 мм 7Н22 с бронебойной пулей используется в автоматических винтовках многих стран - участниц Варшавского договора. Внутри пули находится бронебойный сердечник из твёрдого сплава. Эффективен против бронежилетов.",
                "Армейский патрон калибра 5,45x39 мм 7Н22 с бронебойной пулей используется в автоматических винтовках стран Варшавского договора. Внутри пули находится бронебойный сердечник из твёрдого сплава. Эффективен против бронежилетов.",
                "7cf12ef1cf26c5cff85d8bc9dcdbeb859f6c1ff82e0f1b69c9bba0519a1c60f7")),
        CopFix(
            "cop.localization.upgrade-description-typo",
            "Correct selected weapon upgrade description typo",
            "The Russian upgrade text has an incorrect grammatical ending in its armor modification name.",
            "Corrects that one exact text string; it does not change the upgrade effect or prerequisites.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_items_weapons_upgrades.xml", "st_up_arm_c11_name",
                "Установка более лёгких синтетических и пластиковый частей",
                "Установка более лёгких синтетических и пластиковых частей",
                "5810320de93400c35fdeae59ff0e4485ff4339f971813fd336abef2b3686c718")),
        CopFix(
            "cop.localization.sleep-warning-capitalization",
            "Normalize capitalization in a sleep warning",
            "The Russian UI message inconsistently capitalizes the polite pronoun in the sleep warning text.",
            "Applies the source patch's lowercase form to one stable warning string ID.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/ui_st_screen.xml", "sleep_warning_all_pleasures",
                "Вы не можете спать! У Вас опасное кровотечение и высокий уровень облучённости организма. Используйте медикаменты или обратитесь к медику.",
                "Вы не можете спать! У вас опасное кровотечение и высокий уровень облучённости организма. Используйте медикаменты или обратитесь к медику.",
                "3e5f4c531e93be7d58a4e77ee7bbb94ccb27dc3c78af9befcd27ae3059c5a75f")),
        CopFix(
            "cop.localization.inventory-label-punctuation",
            "Add the missing punctuation to the health sensor label",
            "The Russian inventory label lacks the colon used to introduce its value.",
            "Adds only the punctuation included by the source correction.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/ui_st_inventory.xml", "st_ui_health_sensor",
                "Состояние здоровья",
                "Состояние здоровья:",
                "c75fde55e5ce16dced6adbd8d5ad0ab18fd5292e6e52cad08e132e2bdf99a24b")),
        CopFix(
            "cop.localization.achievement-pronoun-case",
            "Normalize capitalization in an achievement description",
            "The Russian achievement text capitalizes a second-person pronoun inconsistently.",
            "Corrects only the pronoun in one achievement description; scoring and unlock conditions remain unchanged.",
            GameFixCategory.Community,
            CopTextPatch("gamedata/configs/text/rus/st_achievement.xml", "st_achievement_10_descr",
                "Какое унижение для противника! Убитый десять раз, он ни разу не смог Вас достать. Впрочем, ему лучше воспринимать это не как излишнюю жестокость, а как хороший стимул для тренировок.",
                "Какое унижение для противника! Убитый десять раз, он ни разу не смог вас достать. Впрочем, ему лучше воспринимать это не как излишнюю жестокость, а как хороший стимул для тренировок.",
                "92ed1796d73d17ba18954a251de3034b3286a6b9860f54200c59983d1d1afcb0")),
    ];

    public const string DatasetVersion = "2026.09.2";
    public const string PreviousDatasetVersion = "2026.09.1";
    public const GameFixPreset DefaultPreset = GameFixPreset.Recommended;

    public static IReadOnlyList<GameFixDefinition> All => Definitions;

    public static IReadOnlyList<GameFixDefinition> ForGame(GameTarget game) =>
        Definitions.Where(definition => definition.Game == game).ToArray();

    public static IReadOnlyDictionary<GameFixCategory, int> CategoryCounts(GameTarget game) =>
        Enum.GetValues<GameFixCategory>().ToDictionary(
            category => category,
            category => Definitions.Count(definition => definition.Game == game && definition.Category == category));

    /// <summary>Preset counts at the previous shipped catalogue version; update alongside DatasetVersion.</summary>
    public static int PreviousPresetCount(GameTarget game, GameFixPreset preset) =>
        preset == GameFixPreset.Recommended
            ? game switch
            {
                GameTarget.ClearSky => 23,
                GameTarget.ShadowOfChernobyl => 15,
                GameTarget.CallOfPripyat => 5,
                _ => 0,
            }
            : 0;

    /// <summary>Presets never select Experimental or ResearchOnly definitions implicitly.</summary>
    public static IReadOnlyList<GameFixDefinition> ForPreset(GameTarget game, GameFixPreset preset)
    {
        if (preset == GameFixPreset.Custom) return [];
        return Definitions.Where(definition => definition.Game == game && IsIncludedInPreset(definition, preset)).ToArray();
    }

    internal static bool IsIncludedInPreset(GameFixDefinition definition, GameFixPreset preset) =>
        preset != GameFixPreset.Custom &&
        definition.Maturity == GameFixMaturity.Validated &&
        definition.Category != GameFixCategory.Experimental &&
        preset switch
        {
            GameFixPreset.EssentialOnly => definition.Category == GameFixCategory.Essential,
            GameFixPreset.Recommended => definition.Category is GameFixCategory.Essential or GameFixCategory.Recommended,
            GameFixPreset.AllSafeFixes => definition.Category is GameFixCategory.Essential or GameFixCategory.Recommended,
            _ => false,
        };

    public static bool TryGet(string id, out GameFixDefinition? definition)
    {
        definition = Definitions.FirstOrDefault(candidate => string.Equals(candidate.Id, id, StringComparison.Ordinal));
        return definition is not null;
    }

    private static TextPatchOperation Patch(string relativePath, string expectedText, string replacementText, string sourceFileSha256) =>
        new(relativePath, expectedText, replacementText)
        {
            ExpectedFileSha256 = sourceFileSha256,
        };

    private static TextPatchOperation LegacyAggressionPatch(string relativePath, string expectedText, string sourceFileSha256)
    {
        var replacement = expectedText.Contains("aggressive_home = true", StringComparison.Ordinal)
            ? expectedText.Replace("aggressive_home = true", "aggressive = true", StringComparison.Ordinal)
            : expectedText.Replace("aggressive_home", "aggressive = true", StringComparison.Ordinal);
        return Patch(relativePath, expectedText, replacement, sourceFileSha256);
    }

    private static TextPatchOperation RadarDeathPatch(string section, string activeScheme) =>
        Patch("gamedata/config/misc/gulag_radar.ltx",
            $"[logic@{section}]\r\nactive = {activeScheme}\r\ncombat_ignore=combat_ignore\r\non_hit = hit@rad_svoboda\r\non_death = hit@rad_svoboda\r\n",
            $"[logic@{section}]\r\nactive = {activeScheme}\r\ncombat_ignore=combat_ignore\r\non_hit = hit@rad_svoboda\r\non_death = death@rad_svoboda\r\n",
            "f4f86dab8e31df2b46e0589854e3cbb2f60ace2c15eaab895acebfad7af62fc0");

    private static GameFixDefinition SrpFix(
        string id,
        string title,
        string problem,
        string description,
        GameFixCategory category,
        params TextPatchOperation[] patches) =>
        new GameFixDefinition(
            id,
            GameTarget.ClearSky,
            "1.0.0",
            title,
            ["11450472"],
            category,
            GameFixMaturity.Validated,
            [],
            [],
            patches,
            "Adapted from SRP v1.1.5 at Decane/SRP commit dbf6a4bf954ef2de1861ec46eb0eb5aed3b3a5cc.")
        {
            Problem = problem,
            Description = description,
            Implementation = GameFixImplementationType.ExactTextReplacement,
            SaveCompatibility = GameFixSaveCompatibility.Unknown,
            VerificationState = GameFixVerificationState.RetailFilesVerified,
            DetectionMethod = "Steam build 11450472, exact archived source-file SHA-256 per operation, and unique exact text anchors.",
            References =
            [
                "https://github.com/Decane/SRP/blob/dbf6a4bf954ef2de1861ec46eb0eb5aed3b3a5cc/SRP%20v1.1.5%20-%20Version%20History.txt",
                "https://github.com/Decane/SRP/blob/dbf6a4bf954ef2de1861ec46eb0eb5aed3b3a5cc/SRP%20v1.1.5%20-%20Readme.txt",
            ],
        };

    private static GameFixDefinition ZrpFix(
        string id,
        string title,
        string problem,
        string description,
        GameFixCategory category,
        params TextPatchOperation[] patches) =>
        new GameFixDefinition(
            id,
            GameTarget.ShadowOfChernobyl,
            "1.0.0",
            title,
            ["11567845"],
            category,
            GameFixMaturity.Validated,
            [],
            [],
            patches,
            "Adapted from ZRP 1.07 R5RC (8 April 2015), including the accumulated R3-to-R5 fixes in its shipped change notes; target is the verified SoC Steam build only.")
        {
            Problem = problem,
            Description = description,
            Implementation = GameFixImplementationType.ExactTextReplacement,
            SaveCompatibility = GameFixSaveCompatibility.Unknown,
            VerificationState = GameFixVerificationState.RetailFilesVerified,
            DetectionMethod = "Steam build 11567845, exact SHA-256 of each effective file extracted from the local retail archives, and unique exact text anchors.",
            References =
            [
                "https://www.metacognix.com/stlkrsoc/",
                "https://metacognix.com/files/stlkrsoc/index.html",
                "https://www.metacognix.com/stlkrsoc/BugsInSTALKER.html",
            ],
        };

    private static GameFixDefinition CopFix(
        string id,
        string title,
        string problem,
        string description,
        GameFixCategory category,
        params TextPatchOperation[] patches) =>
        new GameFixDefinition(
            id,
            GameTarget.CallOfPripyat,
            "1.0.0",
            title,
            ["11450453"],
            category,
            GameFixMaturity.Validated,
            [],
            [],
            patches,
            "Adapted as narrow exact-text patches from stalker-cop-patch commit 3835ee1b7829fe7c7712af1a7ff97e85e46a906c; retail source is Steam build 11450453.")
        {
            Problem = problem,
            Description = description,
            Implementation = GameFixImplementationType.ExactTextReplacement,
            SaveCompatibility = GameFixSaveCompatibility.Unknown,
            VerificationState = GameFixVerificationState.RetailFilesVerified,
            DetectionMethod = "Steam build 11450453, exact SHA-256 of each effective file extracted from the local retail archives, and unique exact text anchors.",
            References = ["https://github.com/victor-homyakov/stalker-cop-patch/tree/3835ee1b7829fe7c7712af1a7ff97e85e46a906c"],
        };

    private static GameFixDefinition PrpFix(
        string id,
        string title,
        string problem,
        string description,
        GameFixCategory category,
        params TextPatchOperation[] patches) =>
        new GameFixDefinition(
            id,
            GameTarget.CallOfPripyat,
            "1.0.0",
            title,
            ["11450453"],
            category,
            GameFixMaturity.Validated,
            [],
            [],
            patches,
            "PRP v1.2 (Pripyat Reclamation Patch); targeted operation verified against Call of Pripyat Steam build 11450453.")
        {
            Problem = problem,
            Description = description,
            Implementation = GameFixImplementationType.ExactTextReplacement,
            SaveCompatibility = GameFixSaveCompatibility.Unknown,
            VerificationState = GameFixVerificationState.RetailFilesVerified,
            DetectionMethod = "Exact SHA-256 of each effective retail file from Steam build 11450453 and unique exact text anchors; PRP v1.2 archive SHA-256 d4c5b8c3836b7d51b0b175aeb1d5e18896f99dc27f5a7e79955f72638358d598.",
            References =
            [
                "https://www.moddb.com/mods/pripyat-reclamation-patch",
                "https://www.mediafire.com/folder/lo9xufb1io6av/PRP",
            ],
        };

    private static TextPatchOperation CopTextPatch(
        string relativePath,
        string stringId,
        string expectedText,
        string replacementText,
        string sourceFileSha256) =>
        Patch(relativePath,
            $"<string id=\"{stringId}\">\r\n\t\t<text>{expectedText}</text>",
            $"<string id=\"{stringId}\">\r\n\t\t<text>{replacementText}</text>",
            sourceFileSha256) with { CodePage = 1251 };
}
