#!/usr/bin/env python3
"""Generate save_editor_places.script for CoP, CS, and SoC from place_names.json.

Where an official in-game string id exists (st_*_name, st_name_*), stores
the string id so the running game translates it into the active locale.
Where no string id exists in the game configs, stores the fallback text
with source citation in a comment.

Usage: python3 tools/generate_companion_places.py [cop|cs|soc]
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "mods/companion/data/place_names.json"


def extract_id_or_text(info: dict[str, str]) -> tuple[str, bool, str]:
    """Returns (value, is_string_id, source)."""
    src = info.get("source", "")
    # Check for string id in source: e.g. ":st_zat_a2_name" or ":st_name_..."
    m = re.search(r":\s*(st_[a-zA-Z0-9_]+)", src)
    if m:
        return m.group(1), True, src

    # Also check if ru or en is an st_* id
    ru = info.get("ru", "")
    if ru.startswith("st_"):
        return ru, True, src

    return ru, False, src


def generate_for_game(game: str, places: dict[str, dict[str, str]]) -> Path:
    target_dir = ROOT / f"mods/companion/{game}/gamedata/scripts"
    target_dir.mkdir(parents=True, exist_ok=True)
    target_file = target_dir / "save_editor_places.script"

    lines = [
        "--[[",
        f"  S.T.A.L.K.E.R. Save Editor — companion place names for {game.upper()}.",
        "  Generated by tools/generate_companion_places.py from mods/companion/data/place_names.json.",
        "  String ids are translated at runtime via game.translate_string(id).",
        "  Raw text is used only where no native string id exists in the game configs.",
        "--]]",
        "",
        "names = {",
    ]

    for smart, info in sorted(places.items()):
        val, is_id, src = extract_id_or_text(info)
        # Escape any special characters for Lua string literal
        escaped_val = val.replace("\\", "\\\\").replace('"', '\\"')
        if is_id:
            lines.append(f'\t["{smart}"] = "{escaped_val}",')
        else:
            clean_src = src.split("(")[0].strip() if "(" in src else src.strip()
            lines.append(f"\t-- {clean_src}")
            lines.append(f'\t["{smart}"] = "{escaped_val}",')

    lines.append("}\n")

    target_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {target_file} ({len(places)} places)")
    return target_file


def main() -> int:
    if not DATA_FILE.is_file():
        print(f"Error: {DATA_FILE} not found", file=sys.stderr)
        return 1

    with open(DATA_FILE, encoding="utf-8") as f:
        data = json.load(f)

    target_games = [sys.argv[1].lower()] if len(sys.argv) > 1 else ["cop", "cs", "soc"]

    for game in target_games:
        if game not in data:
            print(f"Warning: no data for game '{game}' in {DATA_FILE}", file=sys.stderr)
            continue
        generate_for_game(game, data[game])

    return 0


if __name__ == "__main__":
    sys.exit(main())
