"""Build the companion's NPC spawn list from an unpacked game config tree.

Usage: python3 tools/generate_companion_squads.py <configs-dir> <game>
  <configs-dir>  the game's configs/ folder unpacked from configs.db
  <game>         cop (the only game whose squad system this targets)

Reads misc/squad_descr*.ltx (squads), creatures/spawn_sections_*.ltx
(character_profile of each NPC section), gameplay/npc_profile.xml and
gameplay/character_desc_*.xml (name string and portrait). Writes
mods/companion/<game>/gamedata/scripts/save_editor_squads.script with ids and
string keys only; names are translated by the game at runtime.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HUMAN = {"stalker", "bandit", "dolg", "freedom", "army", "monolith", "killer", "csky", "ecolog", "zombied"}


def read(path: Path) -> str:
    return path.read_bytes().decode("cp1251", errors="replace").replace("\r", "")


def ltx_sections(text: str) -> dict[str, dict[str, str]]:
    sections: dict[str, dict[str, str]] = {}
    current = None
    for raw in text.splitlines():
        line = raw.split(";", 1)[0].strip()
        header = re.match(r"^\[([^\]]+)\]", line)
        if header:
            current = sections.setdefault(header.group(1).strip(), {})
            continue
        if current is not None and "=" in line:
            key, value = line.split("=", 1)
            current[key.strip()] = value.strip()
    return sections


def names(value: str) -> list[str]:
    return [part.strip() for part in value.split(",") if part.strip()]


def main() -> None:
    configs, game = Path(sys.argv[1]), sys.argv[2]
    squads: dict[str, dict[str, str]] = {}
    for path in sorted((configs / "misc").glob("squad_descr*.ltx")):
        squads.update(ltx_sections(read(path)))
    profiles: dict[str, str] = {}
    for path in sorted((configs / "creatures").glob("spawn_sections*.ltx")):
        for section, values in ltx_sections(read(path)).items():
            if "character_profile" in values:
                profiles[section] = values["character_profile"]
    classes = dict(re.findall(r'<character id="([^"]+)">\s*<class>([^<]+)</class>', read(configs / "gameplay/npc_profile.xml")))
    specific: dict[str, tuple[str, str]] = {}
    for path in sorted((configs / "gameplay").glob("character_desc_*.xml")):
        for block in re.findall(r"<specific_character\b.*?</specific_character>", read(path), re.S):
            cls = re.search(r"<class>([^<]+)</class>", block)
            name = re.search(r"<name>([^<]+)</name>", block)
            icon = re.search(r"<icon>([^<]+)</icon>", block)
            if cls and name:
                specific[cls.group(1).strip()] = (name.group(1).strip(), icon.group(1).strip() if icon else "")

    stalkers, mutants, characters = [], [], []
    mutant_by_npc: dict[str, str] = {}
    for sid, values in sorted(squads.items()):
        faction = values.get("faction", "").split()[0] if values.get("faction") else ""
        npc = names(values.get("npc", ""))
        pool = npc or names(values.get("npc_random", ""))
        if not faction or not pool:
            continue
        if faction.startswith("monster"):
            if re.match(r"^(jup|lx8|pas|pri|zat)_", pool[0]):
                continue  # quest-bound variant of a generic creature
            # one group per creature section; prefer simulation squads
            current = mutant_by_npc.get(pool[0])
            if current is None or ("sim" in sid and "sim" not in current):
                mutant_by_npc[pool[0]] = sid
        elif faction in HUMAN and "story_id" in values and len(npc) == 1:
            profile = profiles.get(npc[0], npc[0])
            name, icon = specific.get(classes.get(profile, profile), ("", ""))
            if name:
                characters.append(f'{{ id = "{sid}", name = "{name}", icon = "{icon}", faction = "{faction}" }}')
        elif faction in HUMAN and "story_id" not in values:
            stalkers.append(f'{{ id = "{sid}", faction = "{faction}", size = {len(npc) or 0} }}')

    for npc_section, sid in sorted(mutant_by_npc.items()):
        mutants.append(f'{{ id = "{sid}", npc = "{npc_section}" }}')

    target = ROOT / "mods/companion" / game / "gamedata/scripts/save_editor_squads.script"
    lines = [
        "-- Generated by tools/generate_companion_squads.py from the game's squad descriptions.",
        "-- Do not edit by hand. Names are string keys the game translates.",
        "stalkers = {", *(f"\t{row}," for row in stalkers), "}",
        "mutants = {", *(f"\t{row}," for row in mutants), "}",
        "characters = {", *(f"\t{row}," for row in characters), "}",
    ]
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{target.relative_to(ROOT)}: {len(stalkers)} squads, {len(mutants)} mutant groups, {len(characters)} characters")


if __name__ == "__main__":
    main()
