"""Generate weather preset tables for the companion mod across SoC, CS, CoP.

Usage: python3 tools/generate_companion_weather.py
Writes:
  mods/companion/cop/gamedata/scripts/save_editor_weather.script
  mods/companion/cs/gamedata/scripts/save_editor_weather.script
  mods/companion/soc/gamedata/scripts/save_editor_weather.script
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

WEATHERS_COP = [
    ("default_clear", "Ясно", "Безоблачное чистое небо"),
    ("default_cloudy", "Облачно", "Пасмурно, рассеянный свет"),
    ("default_rain", "Дождь", "Дождливая погода, капли и лужи"),
    ("default_thunder", "Гроза", "Шторм, ливень, гром и молнии"),
    ("night", "Ночь", "Тёмная глухая ночь"),
    ("indoor", "Подземелье", "Освещение лабораторий и подземелий"),
    ("indoor_ambient", "Путепровод", "Подземный эмбиент Припять-1"),
    ("stancia2", "ЧАЭС-2", "Штормовое багровое небо ЧАЭС"),
    ("sun_shafts", "Солнечные лучи", "Ярко выраженные лучи сквозь облака"),
    ("[default]", "По умолчанию", "Базовый погодный цикл"),
]

WEATHERS_CS = [
    ("default_clear", "Ясно", "Безоблачное чистое небо"),
    ("default_cloudy", "Облачно", "Пасмурно, рассеянный свет"),
    ("default_rain", "Дождь", "Дождливая погода, капли и лужи"),
    ("default_thunder", "Гроза", "Шторм, ливень, гром и молнии"),
    ("night", "Ночь", "Тёмная глухая ночь (сцена на Болотах)"),
    ("indoor", "Подземелье", "Освещение подземелий Агропрома"),
    ("stancia2", "ЧАЭС-2", "Финальный шторм на ЧАЭС"),
    ("sun_shafts", "Солнечные лучи", "Ярко выраженные лучи сквозь облака"),
    ("[default]", "По умолчанию", "Базовый погодный цикл"),
]

WEATHERS_SOC = [
    ("default", "По умолчанию / Ясно", "Стандартный погодный цикл Зоны"),
    ("rain", "Дождь", "Затяжной дождь с грозой"),
    ("yantar", "Янтарь", "Тяжёлая желтовато-зелёная мгла"),
    ("radar", "Радар", "Мрачный густой туман и серое небо"),
    ("pripyat", "Припять", "Холодное пасмурное небо Припяти"),
    ("stancia", "ЧАЭС", "Зловещее предгрозовое небо станции"),
    ("stancia2", "ЧАЭС-2", "Бушующий радиоактивный выброс"),
    ("sarkofag", "Саркофаг", "Освещение внутри 4-го энергоблока"),
    ("indoor", "Подземелье", "Освещение катакомб Агропрома"),
    ("indoor_x18", "Лаборатория X-18", "Освещение лаборатории X-18"),
    ("yantar_indoor", "Лаборатория X-16", "Освещение лаборатории под Янтарём"),
]

GAMES = {
    "cop": WEATHERS_COP,
    "cs": WEATHERS_CS,
    "soc": WEATHERS_SOC,
}


def render_lua(items: list[tuple[str, str, str]]) -> str:
    lines = [
        "-- Generated by tools/generate_companion_weather.py.",
        "-- Do not edit by hand.",
        "",
        "list = {",
    ]
    for wid, title, desc in items:
        # Escape quotes if any
        title_esc = title.replace('"', '\\"')
        desc_esc = desc.replace('"', '\\"')
        lines.append(f'\t{{ id = "{wid}", title = "{title_esc}", desc = "{desc_esc}" }},')
    lines.append("}")
    lines.append("weathers = list")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    for game, items in GAMES.items():
        out_path = ROOT / "mods/companion" / game / "gamedata/scripts/save_editor_weather.script"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(render_lua(items), encoding="utf-8")
        print(f"Generated {out_path.relative_to(ROOT)} ({len(items)} weathers)")


if __name__ == "__main__":
    main()
