"""Write the companion's spawn list from the embedded item catalog.

Usage: python3 tools/generate_companion_catalog.py
Writes mods/companion/<game>/gamedata/scripts/save_editor_catalog.script for
Shadow of Chernobyl (soc), Clear Sky (cs) and Call of Pripyat (cop). Item names
are not stored: the mod shows each item's own inv_name from the game, so the
list follows the game's language.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "src/StalkerSaveEditor.Core/Catalogs/Data/catalogs.json"
GAMES = {"stalker-soc": "soc", "stalker-cs": "cs", "stalker-cop": "cop"}
SKIP_PREFIXES = ("mp_",)
SKIP_KEYS = {"helicopter", "mounted_weapon"}
ORDER = ("weapon", "ammo", "outfit", "artifact", "grenade", "consumable", "item")


def render(items: list[dict]) -> str:
    by_category: dict[str, list[str]] = {name: [] for name in ORDER}
    for item in items:
        category = item.get("category")
        key = item["key"]
        if key in SKIP_KEYS or key.startswith(SKIP_PREFIXES):
            continue
        if category in by_category:
            by_category[category].append(item["key"])
    lines = [
        "-- Generated by tools/generate_companion_catalog.py from the editor's item catalog.",
        "-- Do not edit by hand.",
        "items = {",
    ]
    for category in ORDER:
        keys = ", ".join(f'"{key}"' for key in sorted(by_category[category]))
        lines.append(f"\t{category} = {{ {keys} }},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    releases = json.loads(CATALOG.read_text(encoding="utf-8"))["releases"]
    for release, folder in GAMES.items():
        target = ROOT / "mods/companion" / folder / "gamedata/scripts/save_editor_catalog.script"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(releases[release]["items"]), encoding="utf-8")
        print(target.relative_to(ROOT))


if __name__ == "__main__":
    main()
